/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package starter


// Main function
fun main() {
    val name = "Aditya Kesuma";
    print("Hello My name is ");
    println(name);
    print(if(true) "always True" else "always False");
    cetakLineSpasi();
    dataType();
    cetakLineSpasi();

    val valueA : Int = 10;
    val valueB = 20;
    print(valueA + valueB);

    cetakLineSpasi();

    val text  = "Kotlin";
    val firstChar = text[0];
 
    print("First character of $text is $firstChar")
    cetakLineSpasi();

    for (char in text){
        print("$char ")
    }

    cetakLineSpasi();
    println("Kotlin is \"Awesome!\"");
    cetakLineSpasi();

    printUser(text);
    cetakLineSpasi();

    // Nullable datatype
    val text2 : String? = null;

    if(text2 != null){
        val textLength = text2.length;
    }

    // Safe Call Operator

    /*Yang pertama akan kita pelajari adalah Safe Calls. Seperti namanya, safe call akan menjamin
     kode yang kita tulis aman dari NullPointerException. Dalam menggunakan safe call, kita akan
      mengganti tanda titik (.) dengan tanda (?.) saat mengakses atau mengelola nilai dari objek nullable.
       Seperti ini:  */
    
    text2?.length


    // Elvis Operator(?:)
     /*YElvis operator memungkinkan kita untuk menetapkan default value atau nilai dasar jika objek bernilai null. */
    val textLength = text2?.length ?: 7;

    cetakLineSpasi();
    
    // String Template
    // Kita dapat menggunakan ${} untuk 
      val hour = 7
    print("Office ${if (hour > 7) "already close" else "is open"}")
}

// Data Types dan Variable
// val = tidak bisa dirubah
// var = bisa dirubah
fun dataType(){
    var company: String = "dicoding";
    company = "Dicoding Academy";
    println(company);
}

fun cetakLineSpasi(){
    for(i in 1..3){
        println("");
    }
}

// Function
fun setUser(name: String, age:Int): String{
     return "Your name is $name, and you $age years old";
}

// Shorthand function
fun setUser2(name: String, age: Int): String = "Your name is $name, and you $age years old"

// Void menggunakan Unit
fun printUser(name: String): Unit {
    print("Your name is $name")
}

